# VIO 83 AI ORCHESTRA — Sponsorship Links
# These links appear as "Sponsor" button on the GitHub repository

github: [vio83]
ko_fi: vio83
custom: ["https://www.linkedin.com/in/viorica-porcu-637735139"]
